version: '3'

services:
  go-observe:
    build: .
    container_name: go-observe-container
    ports:
      # 1323 で内部的に go が待ち構えている
      # 1340 で localhost からアクセスできる
      - 1340:1323
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:0.107.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"   # OTLP HTTP receiver
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      # 3200 で待機する
      # otel-collector:4318 から tempo:3200 で OTel 形式でメトリクスがエクスポートされる
      - "3200:3200"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
