apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  selector:
    matchLabels:
      app: apache-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: apache-pod
    spec:
      containers:
        - name: apache-container
          image: httpd
          ports:
            - containerPort: 80
